---
# tasks file for install_pkg

- name: Include OS-specific variables
  include_tasks: variables.yml

- name: remove packages
  include_tasks: install.yml
  loop: "{{ package_list }}"
  loop_control:
    loop_var: package_name